name: Deploy

on:
  push:
    branches:
      - 'deploy/prod'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build and deploy Contember to production
        run: yarn run deploy ${{ secrets.CONTEMBER_DEPLOY_DSN }} --yes
