/**
 * Builds the panel UI and embeds it into `src/generated/assets.ts`.
 *
 * The engine docker image contains a single bundled `dist/start.js` and nothing else, so there is no
 * directory to serve static files from — the assets travel inside the bundle. Everything is stored
 * gzipped so the payload stays close to what a browser would download anyway, and so the controller
 * can hand the bytes over without compressing per request.
 */
import { spawnSync } from 'node:child_process'
import { constants as zlibConstants, gzipSync } from 'node:zlib'
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve, sep } from 'node:path'

const packageDir = resolve(import.meta.dir, '..')
const uiDir = resolve(packageDir, '../panel-ui')
const distDir = join(uiDir, 'dist')
const outputFile = join(packageDir, 'src/generated/assets.ts')

const contentTypes: Record<string, string> = {
	'.css': 'text/css; charset=utf-8',
	'.html': 'text/html; charset=utf-8',
	'.ico': 'image/x-icon',
	'.js': 'text/javascript; charset=utf-8',
	'.json': 'application/json; charset=utf-8',
	'.png': 'image/png',
	'.svg': 'image/svg+xml',
	'.webp': 'image/webp',
	'.woff2': 'font/woff2',
}

const contentTypeOf = (path: string): string => {
	const ext = path.slice(path.lastIndexOf('.'))
	return contentTypes[ext] ?? 'application/octet-stream'
}

const listFiles = (dir: string): string[] =>
	readdirSync(dir, { withFileTypes: true }).flatMap(entry => {
		const path = join(dir, entry.name)
		return entry.isDirectory() ? listFiles(path) : [path]
	})

const build = spawnSync('bun', ['run', 'build'], { cwd: uiDir, stdio: 'inherit' })
if (build.status !== 0) {
	throw new Error('Failed to build @contember/panel-ui.')
}

// Source maps would roughly double the embedded payload and hand out the console's sources; the
// panel is debugged from a dev build.
const files = listFiles(distDir).filter(it => !it.endsWith('.map'))
if (!files.some(it => relative(distDir, it) === 'index.html')) {
	throw new Error(`No index.html in ${distDir} — the panel build produced nothing usable.`)
}

let totalRaw = 0
let totalGzip = 0
const entries = files
	.map(file => {
		const path = relative(distDir, file).split(sep).join('/')
		const raw = readFileSync(file)
		const gzip = gzipSync(raw, { level: zlibConstants.Z_BEST_COMPRESSION })
		totalRaw += raw.byteLength
		totalGzip += gzip.byteLength
		return `\t${JSON.stringify(path)}: { contentType: ${JSON.stringify(contentTypeOf(path))}, gzip: ${JSON.stringify(gzip.toString('base64'))} },`
	})
	.sort()

const output = `import type { PanelAssetMap } from '../PanelAssets.js'

// Generated by scripts/buildAssets.ts — do not edit.
export const panelAssets: PanelAssetMap = {
${entries.join('\n')}
}
`

mkdirSync(dirname(outputFile), { recursive: true })
writeFileSync(outputFile, output)

const kb = (bytes: number) => `${(bytes / 1024).toFixed(1)} kB`
console.log(`engine-panel: embedded ${files.length} files, ${kb(totalRaw)} raw / ${kb(totalGzip)} gzipped (${kb(output.length)} of source).`)
