export type AuthActionType =
	| 'login'
	| 'create_session_token'
	| 'idp_login'
	| 'password_reset_init'
	| 'password_reset'
	| 'password_change'
	| 'email_change'
	| '2fa_disable'
	| '2fa_enable'
	| 'passwordless_login_init'
	| 'passwordless_login_exchange'
	| 'passwordless_login'
	| 'person_disable'
