version: '2.4'

services:
  admin:
    user: '1000:1000'
    environment:
      VITE_PORT: 1480
      VITE_CONTEMBER_ADMIN_API_BASE_URL: http://localhost:1481
    ports:
      - '1480:1480' # ports must match

  contember:
    ports:
      - '1481:4000'
    environment:
      DEFAULT_S3_ENDPOINT: 'http://localhost:1483'

  contember-cli:
    user: '1000:1000'
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

  contember-migrations:
    user: '1000:1000'
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

  postgresql:
    ports:
      - '1482:5432'

  s3:
    ports:
      - '1483:1483' # ports must match
    command: 'server --address :1483 /data'

  mailhog:
    ports:
      - '1484:8025'

  adminer:
    ports:
      - '1485:8080'
