export { GoogleFormEmbedHandler as GoogleForm } from './GoogleFormEmbedHandler'
export { SoundCloudEmbedHandler as SoundCloud } from './SoundCloudEmbedHandler'
export { SpotifyEmbedHandler as Spotify } from './SpotifyEmbedHandler'
export { VimeoEmbedHandler as Vimeo } from './VimeoEmbedHandler'
export { YouTubeEmbedHandler as YouTube } from './YouTubeEmbedHandler'
