export { GoogleFormEmbedHandler as GoogleForm } from './GoogleFormEmbedHandler.js'
export { SoundCloudEmbedHandler as SoundCloud } from './SoundCloudEmbedHandler.js'
export { SpotifyEmbedHandler as Spotify } from './SpotifyEmbedHandler.js'
export { VimeoEmbedHandler as Vimeo } from './VimeoEmbedHandler.js'
export { YouTubeEmbedHandler as YouTube } from './YouTubeEmbedHandler.js'
