import {
	anchorToolbarButton,
	boldToolbarButton,
	codeToolbarButton,
	headingFiveNumberedToolbarButton,
	headingFiveToolbarButton,
	headingFourNumberedToolbarButton,
	headingFourToolbarButton,
	headingOneNumberedToolbarButton,
	headingOneToolbarButton,
	headingSixNumberedToolbarButton,
	headingSixToolbarButton,
	headingThreeNumberedToolbarButton,
	headingThreeToolbarButton,
	headingTwoNumberedToolbarButton,
	headingTwoToolbarButton,
	highlightToolbarButton,
	horizontalRuleToolbarButton,
	italicToolbarButton,
	orderedListToolbarButton,
	scrollTargetToolbarButton,
	strikeThroughToolbarButton,
	tableToolbarButton,
	underlineToolbarButton,
	unorderedListToolbarButton,
} from './plugins'

export namespace RichEditor {
	export const buttons = {
		anchor: anchorToolbarButton,
		headingOne: headingOneToolbarButton,
		headingOneNumbered: headingOneNumberedToolbarButton,
		headingTwo: headingTwoToolbarButton,
		headingTwoNumbered: headingTwoNumberedToolbarButton,
		headingThree: headingThreeToolbarButton,
		headingThreeNumbered: headingThreeNumberedToolbarButton,
		headingFour: headingFourToolbarButton,
		headingFourNumbered: headingFourNumberedToolbarButton,
		headingFive: headingFiveToolbarButton,
		headingFiveNumbered: headingFiveNumberedToolbarButton,
		headingSix: headingSixToolbarButton,
		headingSixNumbered: headingSixNumberedToolbarButton,
		horizontalRule: horizontalRuleToolbarButton,
		orderedList: orderedListToolbarButton,
		scrollTarget: scrollTargetToolbarButton,
		unorderedList: unorderedListToolbarButton,
		table: tableToolbarButton,

		bold: boldToolbarButton,
		code: codeToolbarButton,
		highlight: highlightToolbarButton,
		italic: italicToolbarButton,
		strikeThrough: strikeThroughToolbarButton,
		underline: underlineToolbarButton,
	}
}
