import './cases/unit/model/markerTreeGenerator.spec'
import './cases/unit/queryLanguage/filter.spec'
import './cases/unit/queryLanguage/general.spec'
import './cases/unit/queryLanguage/orderBy.spec'
import './cases/unit/queryLanguage/qualifiedEntityList.spec'
import './cases/unit/queryLanguage/qualifiedFieldList.spec'
import './cases/unit/queryLanguage/relativeEntityList.spec'
import './cases/unit/queryLanguage/singleRelativeField.spec'
