import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
	mainSidebar: [
		{
			type: 'category',
			label: 'Getting Started',
			collapsed: false,
			items: [
				{
					type: 'doc',
					id: 'intro/introduction',
					label: 'Overview',
				},
				{
					type: 'doc',
					id: 'intro/how-it-works',
					label: 'How Contember works',
				},
				'intro/glossary',
			],
		},

		{
			type: 'category',
			label: 'Contember Basics',
			collapsed: false,
			items: [
				{
					type: 'doc',
					id: 'intro/installation',
					label: 'Installation',
				},
				{
					type: 'doc',
					id: 'intro/quickstart',
					label: 'Designing your data model',
				},
				{
					type: 'doc',
					id: 'intro/graphql',
					label: 'Handling data with GraphQL',
				},
				'intro/interface',
				'intro/deployment',
				'intro/actions',
			],
		},

		{
			type: 'category',
			label: 'Contember Interface',
			collapsed: true,
			items: [
				'reference/interface/introduction',
				{
					type: 'category',
					label: 'Pages and routing',
					collapsed: true,
					items: [
						{
							type: 'doc',
							id: 'reference/interface/pages/overview',
							label: 'Overview',
						},
						'reference/interface/pages/routing',
						'reference/interface/pages/links',
						'reference/interface/pages/slots',
					],
				},
				{
					type: 'category',
					label: 'Binding',
					collapsed: true,
					items: [
						{
							type: 'doc',
							id: 'reference/interface/data-binding/overview',
							label: 'Overview',
						},
						'reference/interface/data-binding/query-language',
						'reference/interface/data-binding/value-rendering',
						'reference/interface/data-binding/relationship-components',
						'reference/interface/data-binding/custom-components',
					],
				},
				{
					type: 'category',
					label: 'Headless Components',
					collapsed: true,
					items: [
						{
							type: 'doc',
							id: 'reference/interface/headless-components/overview',
							label: 'Overview',
						},
						'reference/interface/headless-components/dataview',
					],
				},
				{
					type: 'category',
					label: 'UI Components',
					collapsed: true,
					items: [
						{
							type: 'doc',
							id: 'reference/interface/ui-components/overview',
							label: 'Overview',
						},
						'reference/interface/ui-components/anchor-renderer',
						'reference/interface/ui-components/audio-field',
						'reference/interface/ui-components/audio-repeater-field',
						'reference/interface/ui-components/back-button',
						'reference/interface/ui-components/back-button-label',
						'reference/interface/ui-components/base-editor-plugins',
						'reference/interface/ui-components/binding',
						'reference/interface/ui-components/block-editor-field',
						'reference/interface/ui-components/block-editor-handle',
						'reference/interface/ui-components/block-editor-inner',
						'reference/interface/ui-components/block-editor-plugins',
						'reference/interface/ui-components/block-element',
						'reference/interface/ui-components/checkbox-field',
						'reference/interface/ui-components/create-component-open-hooks',
						'reference/interface/ui-components/create-entity-dialog',
						'reference/interface/ui-components/datagrid',
						'reference/interface/ui-components/default-block-repeater',
						'reference/interface/ui-components/default-board',
						'reference/interface/ui-components/default-repeater',
						'reference/interface/ui-components/default-select-data-view',
						'reference/interface/ui-components/delete-entity-dialog',
						'reference/interface/ui-components/dimensions-switcher',
						'reference/interface/ui-components/editor-block',
						'reference/interface/ui-components/editor-block-content',
						'reference/interface/ui-components/editor-block-toolbar',
						'reference/interface/ui-components/editor-canvas',
						'reference/interface/ui-components/editor-editable-canvas',
						'reference/interface/ui-components/editor-inline-toolbar',
						'reference/interface/ui-components/error-boundary',
						'reference/interface/ui-components/file-field',
						'reference/interface/ui-components/file-repeater-field',
						'reference/interface/ui-components/form-container',
						'reference/interface/ui-components/form-field-label',
						'reference/interface/ui-components/formatted-field',
						'reference/interface/ui-components/heading-renderer',
						'reference/interface/ui-components/horizontal-rule-renderer',
						'reference/interface/ui-components/identity-loader',
						'reference/interface/ui-components/image-field',
						'reference/interface/ui-components/image-repeater-field',
						'reference/interface/ui-components/input-field',
						'reference/interface/ui-components/layout-boxed-component',
						'reference/interface/ui-components/layout-component',
						'reference/interface/ui-components/link-back-button',
						'reference/interface/ui-components/list-item-renderer',
						'reference/interface/ui-components/login-with-email',
						'reference/interface/ui-components/multi-select-field',
						'reference/interface/ui-components/multi-select-input',
						'reference/interface/ui-components/multi-select-item-content-ui',
						'reference/interface/ui-components/multi-select-item-drag-overlay-ui',
						'reference/interface/ui-components/multi-select-item-remove-button-ui',
						'reference/interface/ui-components/multi-select-item-ui',
						'reference/interface/ui-components/multi-select-sortable-item-content-ui',
						'reference/interface/ui-components/navigation-guard-dialog',
						'reference/interface/ui-components/ordered-list-renderer',
						'reference/interface/ui-components/outdated-application-dialog',
						'reference/interface/ui-components/paragraph-renderer',
						'reference/interface/ui-components/persist-button',
						'reference/interface/ui-components/radio-enum-field',
						'reference/interface/ui-components/repeater-add-item-button',
						'reference/interface/ui-components/repeater-drop-indicator',
						'reference/interface/ui-components/repeater-item-actions',
						'reference/interface/ui-components/repeater-remove-item-button',
						'reference/interface/ui-components/rich-text-field',
						'reference/interface/ui-components/rich-text-field-plugins',
						'reference/interface/ui-components/rich-text-view',
						'reference/interface/ui-components/scroll-target-renderer',
						'reference/interface/ui-components/select-default-filter',
						'reference/interface/ui-components/select-default-placeholder-ui',
						'reference/interface/ui-components/select-field',
						'reference/interface/ui-components/select-input',
						'reference/interface/ui-components/select-input-actions-ui',
						'reference/interface/ui-components/select-input-ui',
						'reference/interface/ui-components/select-input-wrapper-ui',
						'reference/interface/ui-components/select-list-inner',
						'reference/interface/ui-components/select-list-item-ui',
						'reference/interface/ui-components/select-popover-content',
						'reference/interface/ui-components/side-dimensions',
						'reference/interface/ui-components/sortable-block',
						'reference/interface/ui-components/sortable-multi-select-input',
						'reference/interface/ui-components/standalone-form-container',
						'reference/interface/ui-components/textarea-field',
						'reference/interface/ui-components/title',
						'reference/interface/ui-components/toaster',
						'reference/interface/ui-components/todo',
						'reference/interface/ui-components/uploaded-any-view',
						'reference/interface/ui-components/uploaded-audio-view',
						'reference/interface/ui-components/uploaded-image-view',
						'reference/interface/ui-components/uploaded-video-view',
						'reference/interface/ui-components/uploader-dropzone',
						'reference/interface/ui-components/uploader-dropzone-area-ui',
						'reference/interface/ui-components/uploader-dropzone-wrapper-ui',
						'reference/interface/ui-components/uploader-file-progress-ui',
						'reference/interface/ui-components/uploader-item-ui',
						'reference/interface/ui-components/uploader-progress',
						'reference/interface/ui-components/use-show-toast',
						'reference/interface/ui-components/video-field',
						'reference/interface/ui-components/video-repeater-field',
					],
				},
			],
		},
		{
			type: 'category',
			label: 'Contember Engine',
			collapsed: true,
			items: [
				{
					type: 'category',
					label: 'Schema',
					collapsed: true,
					items: [
						'reference/engine/schema/overview',
						'reference/engine/schema/columns',
						'reference/engine/schema/relationships',
						'reference/engine/schema/views',
						'reference/engine/schema/acl',
						'reference/engine/schema/tenant-acl',
						'reference/engine/schema/validations',
					],
				},
				{
					type: 'category',
					label: 'Migrations',
					collapsed: true,
					items: [
						'reference/engine/migrations/overview',
						'reference/engine/migrations/basics',
						'reference/engine/migrations/content-migrations',
						{
							type: 'category',
							label: 'Advanced',
							items: [
								'reference/engine/migrations/advanced/development-commands',
								'reference/engine/migrations/advanced/skipping-validations',
								'reference/engine/migrations/advanced/writing-schema-migrations',
							],
						},
					],
				},
				{
					type: 'category',
					label: 'Content API',
					items: [
						'reference/engine/content/overview',
						'reference/engine/content/queries',
						'reference/engine/content/mutations',
						'reference/engine/content/s3',
						'reference/engine/content/event-log',
						'reference/engine/content/transfer',
						{
							type: 'category',
							label: 'Advanced',
							items: [
								'reference/engine/content/advanced/assume-identity',
								'reference/engine/content/advanced/assume-membership',
								'reference/engine/content/advanced/request-debugging',
								'reference/engine/content/advanced/caching',
							],
						},
					],
				},
				{
					type: 'category',
					label: 'Tenant API',
					items: [
						'reference/engine/tenant/overview',
						'reference/engine/tenant/sessions',
						'reference/engine/tenant/invites',
						'reference/engine/tenant/memberships',
						'reference/engine/tenant/api-keys',
						'reference/engine/tenant/idp',
						'reference/engine/tenant/passwordless',
						'reference/engine/tenant/mail-templates',
						'reference/engine/tenant/password-policy',
					],
				},
				{
					type: 'category',
					label: 'Actions',
					items: [
						{
							type: 'doc',
							id: 'reference/engine/actions/overview',
							label: 'Overview',
						},
						'reference/engine/actions/definition',
						'reference/engine/actions/managing',
						'reference/engine/actions/invocation',
					],
				},
			],
		},
		'reference/cli',
		{
			type: 'category',
			label: 'Contember Cloud',
			collapsed: true,
			items: [
				'guides/deploy-contember',
				'cloud/permissions',
			],
		},
		{
			type: 'category',
			label: 'Guides',
			collapsed: true,
			items: [
				'guides/deploy-github-actions',
				'guides/self-hosted-contember',
				'guides/seo',
				'guides/acl-definition',
				'guides/superface',
			],
		},
	],
}


export default sidebars
