import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
	mainSidebar: [
		{
			type: 'category',
			label: 'Getting Started',
			collapsed: false,
			items: [
				{
					type: 'doc',
					id: 'intro/introduction',
					label: 'Overview',
				},
				{
					type: 'doc',
					id: 'intro/how-it-works',
					label: 'How Contember works',
				},
				'intro/glossary',
			],
		},

		{
			type: 'category',
			label: 'Contember Basics',
			collapsed: false,
			items: [
				{
					type: 'doc',
					id: 'intro/installation',
					label: 'Installation',
				},
				{
					type: 'doc',
					id: 'intro/quickstart',
					label: 'Designing your data model',
				},
				{
					type: 'doc',
					id: 'intro/graphql',
					label: 'Handling data with GraphQL',
				},
				'intro/interface',
				'intro/deployment',
				'intro/actions',
			],
		},

		{
			type: 'category',
			label: 'Contember Interface',
			collapsed: true,
			items: [
				'reference/interface/introduction',
				{
					type: 'category',
					label: 'Pages and routing',
					collapsed: true,
					items: [
						{
							type: 'doc',
							id: 'reference/interface/pages/overview',
							label: 'Overview',
						},
						'reference/interface/pages/routing',
						'reference/interface/pages/links',
						'reference/interface/pages/slots',
					],
				},
				{
					type: 'category',
					label: 'Binding',
					collapsed: true,
					items: [
						{
							type: 'doc',
							id: 'reference/interface/data-binding/overview',
							label: 'Overview',
						},
						'reference/interface/data-binding/query-language',
						'reference/interface/data-binding/value-rendering',
						'reference/interface/data-binding/relationship-components',
						'reference/interface/data-binding/custom-components',
					],
				},
				{
					type: 'category',
					label: 'Headless Components',
					collapsed: true,
					items: [
						{
							type: 'doc',
							id: 'reference/interface/headless-components/overview',
							label: 'Overview',
						},
						'reference/interface/headless-components/dataview',
					],
				},
				// {
				// 	type: 'category',
				// 	label: 'UI Components',
				// 	collapsed: true,
				// 	items: [
				// 		{
				// 			type: 'doc',
				// 			id: 'reference/interface/ui-components/overview',
				// 			label: 'Overview',
				// 		},
				// 		'reference/interface/ui-components/alert-dialog-action',
				// 		'reference/interface/ui-components/alert-dialog-cancel',
				// 		'reference/interface/ui-components/alert-dialog-content',
				// 		'reference/interface/ui-components/alert-dialog-description',
				// 		'reference/interface/ui-components/alert-dialog-footer',
				// 		'reference/interface/ui-components/alert-dialog-header',
				// 		'reference/interface/ui-components/alert-dialog-title',
				// 		'reference/interface/ui-components/alert-dialog-trigger',
				// 		'reference/interface/ui-components/anchor-button',
				// 		'reference/interface/ui-components/anchor-renderer',
				// 		'reference/interface/ui-components/api-key-list',
				// 		'reference/interface/ui-components/audio-field',
				// 		'reference/interface/ui-components/audio-repeater-field',
				// 		'reference/interface/ui-components/avatar',
				// 		'reference/interface/ui-components/avatar-fallback',
				// 		'reference/interface/ui-components/back-button',
				// 		'reference/interface/ui-components/back-button-label',
				// 		'reference/interface/ui-components/base-editor-plugins',
				// 		'reference/interface/ui-components/binding',
				// 		'reference/interface/ui-components/block-editor-field',
				// 		'reference/interface/ui-components/block-editor-handle',
				// 		'reference/interface/ui-components/block-editor-inner',
				// 		'reference/interface/ui-components/block-editor-plugins',
				// 		'reference/interface/ui-components/block-element',
				// 		'reference/interface/ui-components/button',
				// 		'reference/interface/ui-components/card',
				// 		'reference/interface/ui-components/card-content',
				// 		'reference/interface/ui-components/card-description',
				// 		'reference/interface/ui-components/card-footer',
				// 		'reference/interface/ui-components/card-header',
				// 		'reference/interface/ui-components/card-title',
				// 		'reference/interface/ui-components/change-my-password-form-fields',
				// 		'reference/interface/ui-components/checkbox-field',
				// 		'reference/interface/ui-components/checkbox-input',
				// 		'reference/interface/ui-components/collapsible-content',
				// 		'reference/interface/ui-components/collapsible-trigger',
				// 		'reference/interface/ui-components/create-api-key-form-fields',
				// 		'reference/interface/ui-components/create-component-open-hooks',
				// 		'reference/interface/ui-components/create-data-grid-date-range',
				// 		'reference/interface/ui-components/create-entity-dialog',
				// 		'reference/interface/ui-components/data-grid',
				// 		'reference/interface/ui-components/data-grid-action-column',
				// 		'reference/interface/ui-components/data-grid-active-filter-ui',
				// 		'reference/interface/ui-components/data-grid-auto-export',
				// 		'reference/interface/ui-components/data-grid-boolean-column',
				// 		'reference/interface/ui-components/data-grid-boolean-filter',
				// 		'reference/interface/ui-components/data-grid-boolean-filter-controls',
				// 		'reference/interface/ui-components/data-grid-column',
				// 		'reference/interface/ui-components/data-grid-column-header',
				// 		'reference/interface/ui-components/data-grid-column-leaf',
				// 		'reference/interface/ui-components/data-grid-date-column',
				// 		'reference/interface/ui-components/data-grid-date-filter',
				// 		'reference/interface/ui-components/data-grid-date-filter-controls',
				// 		'reference/interface/ui-components/data-grid-date-time-column',
				// 		'reference/interface/ui-components/data-grid-enum-cell',
				// 		'reference/interface/ui-components/data-grid-enum-column',
				// 		'reference/interface/ui-components/data-grid-enum-field-tooltip',
				// 		'reference/interface/ui-components/data-grid-enum-filter',
				// 		'reference/interface/ui-components/data-grid-enum-filter-controls',
				// 		'reference/interface/ui-components/data-grid-enum-list-cell',
				// 		'reference/interface/ui-components/data-grid-enum-list-column',
				// 		'reference/interface/ui-components/data-grid-enum-list-filter',
				// 		'reference/interface/ui-components/data-grid-exclude-action-button-ui',
				// 		'reference/interface/ui-components/data-grid-filter-action-button-ui',
				// 		'reference/interface/ui-components/data-grid-filter-mobile-hiding',
				// 		'reference/interface/ui-components/data-grid-filter-select-item-ui',
				// 		'reference/interface/ui-components/data-grid-filter-select-trigger-ui',
				// 		'reference/interface/ui-components/data-grid-has-many-cell',
				// 		'reference/interface/ui-components/data-grid-has-many-column',
				// 		'reference/interface/ui-components/data-grid-has-many-filter',
				// 		'reference/interface/ui-components/data-grid-has-many-tooltip',
				// 		'reference/interface/ui-components/data-grid-has-one-cell',
				// 		'reference/interface/ui-components/data-grid-has-one-column',
				// 		'reference/interface/ui-components/data-grid-has-one-filter',
				// 		'reference/interface/ui-components/data-grid-has-one-tooltip',
				// 		'reference/interface/ui-components/data-grid-is-defined-column',
				// 		'reference/interface/ui-components/data-grid-is-defined-filter',
				// 		'reference/interface/ui-components/data-grid-is-defined-filter-controls',
				// 		'reference/interface/ui-components/data-grid-layout-switcher',
				// 		'reference/interface/ui-components/data-grid-loader',
				// 		'reference/interface/ui-components/data-grid-no-results',
				// 		'reference/interface/ui-components/data-grid-null-filter',
				// 		'reference/interface/ui-components/data-grid-number-column',
				// 		'reference/interface/ui-components/data-grid-number-filter',
				// 		'reference/interface/ui-components/data-grid-number-filter-controls',
				// 		'reference/interface/ui-components/data-grid-pagination',
				// 		'reference/interface/ui-components/data-grid-per-page-selector',
				// 		'reference/interface/ui-components/data-grid-query-filter',
				// 		'reference/interface/ui-components/data-grid-relation-filter-controls',
				// 		'reference/interface/ui-components/data-grid-relation-filtered-items-list',
				// 		'reference/interface/ui-components/data-grid-show-filters-context',
				// 		'reference/interface/ui-components/data-grid-single-filter-ui',
				// 		'reference/interface/ui-components/data-grid-table',
				// 		'reference/interface/ui-components/data-grid-text-column',
				// 		'reference/interface/ui-components/data-grid-text-filter',
				// 		'reference/interface/ui-components/data-grid-text-filter-inner',
				// 		'reference/interface/ui-components/data-grid-tiles',
				// 		'reference/interface/ui-components/data-grid-toolbar',
				// 		'reference/interface/ui-components/data-grid-toolbar-ui',
				// 		'reference/interface/ui-components/data-grid-toolbar-visible-elements',
				// 		'reference/interface/ui-components/data-grid-tooltip-label',
				// 		'reference/interface/ui-components/data-grid-union-text-filter',
				// 		'reference/interface/ui-components/data-grid-uuid-column',
				// 		'reference/interface/ui-components/data-view-field-label',
				// 		'reference/interface/ui-components/data-view-has-many-label',
				// 		'reference/interface/ui-components/data-view-has-one-label',
				// 		'reference/interface/ui-components/datagrid',
				// 		'reference/interface/ui-components/default-block-repeater',
				// 		'reference/interface/ui-components/default-board',
				// 		'reference/interface/ui-components/default-data-grid',
				// 		'reference/interface/ui-components/default-dropdown',
				// 		'reference/interface/ui-components/default-repeater',
				// 		'reference/interface/ui-components/default-select-data-view',
				// 		'reference/interface/ui-components/delete-entity-dialog',
				// 		'reference/interface/ui-components/dialog-close',
				// 		'reference/interface/ui-components/dialog-content',
				// 		'reference/interface/ui-components/dialog-description',
				// 		'reference/interface/ui-components/dialog-footer',
				// 		'reference/interface/ui-components/dialog-header',
				// 		'reference/interface/ui-components/dialog-title',
				// 		'reference/interface/ui-components/dialog-trigger',
				// 		'reference/interface/ui-components/dimensions-switcher',
				// 		'reference/interface/ui-components/divider',
				// 		'reference/interface/ui-components/drop-down-trigger-button',
				// 		'reference/interface/ui-components/drop-indicator',
				// 		'reference/interface/ui-components/dropdown-menu-content',
				// 		'reference/interface/ui-components/dropdown-menu-group',
				// 		'reference/interface/ui-components/dropdown-menu-item',
				// 		'reference/interface/ui-components/dropdown-menu-label',
				// 		'reference/interface/ui-components/dropdown-menu-portal',
				// 		'reference/interface/ui-components/dropdown-menu-radio-group',
				// 		'reference/interface/ui-components/dropdown-menu-radio-item',
				// 		'reference/interface/ui-components/dropdown-menu-separator',
				// 		'reference/interface/ui-components/dropdown-menu-sub-trigger',
				// 		'reference/interface/ui-components/dropdown-menu-trigger',
				// 		'reference/interface/ui-components/editor-block',
				// 		'reference/interface/ui-components/editor-block-content',
				// 		'reference/interface/ui-components/editor-block-toolbar',
				// 		'reference/interface/ui-components/editor-canvas',
				// 		'reference/interface/ui-components/editor-editable-canvas',
				// 		'reference/interface/ui-components/editor-inline-toolbar',
				// 		'reference/interface/ui-components/error-boundary',
				// 		'reference/interface/ui-components/file-field',
				// 		'reference/interface/ui-components/file-repeater-field',
				// 		'reference/interface/ui-components/form-container',
				// 		'reference/interface/ui-components/form-container-ui',
				// 		'reference/interface/ui-components/form-description-ui',
				// 		'reference/interface/ui-components/form-error-ui',
				// 		'reference/interface/ui-components/form-field-label',
				// 		'reference/interface/ui-components/form-label-ui',
				// 		'reference/interface/ui-components/form-label-wrapper-ui',
				// 		'reference/interface/ui-components/form-layout',
				// 		'reference/interface/ui-components/formatted-field',
				// 		'reference/interface/ui-components/heading-renderer',
				// 		'reference/interface/ui-components/horizontal-rule-renderer',
				// 		'reference/interface/ui-components/identity-loader',
				// 		'reference/interface/ui-components/image-field',
				// 		'reference/interface/ui-components/image-repeater-field',
				// 		'reference/interface/ui-components/input',
				// 		'reference/interface/ui-components/input-bare',
				// 		'reference/interface/ui-components/input-field',
				// 		'reference/interface/ui-components/input-like',
				// 		'reference/interface/ui-components/invite-form-fields',
				// 		'reference/interface/ui-components/label',
				// 		'reference/interface/ui-components/layout-boxed-component',
				// 		'reference/interface/ui-components/layout-component',
				// 		'reference/interface/ui-components/link-back-button',
				// 		'reference/interface/ui-components/list-item-renderer',
				// 		'reference/interface/ui-components/loader',
				// 		'reference/interface/ui-components/loader-icon',
				// 		'reference/interface/ui-components/login-form-fields',
				// 		'reference/interface/ui-components/login-with-email',
				// 		'reference/interface/ui-components/member-delete-dialog',
				// 		'reference/interface/ui-components/member-list',
				// 		'reference/interface/ui-components/memberships-control',
				// 		'reference/interface/ui-components/menu',
				// 		'reference/interface/ui-components/menu-item',
				// 		'reference/interface/ui-components/multi-select-field',
				// 		'reference/interface/ui-components/multi-select-input',
				// 		'reference/interface/ui-components/multi-select-item-content-ui',
				// 		'reference/interface/ui-components/multi-select-item-drag-overlay-ui',
				// 		'reference/interface/ui-components/multi-select-item-remove-button-ui',
				// 		'reference/interface/ui-components/multi-select-item-ui',
				// 		'reference/interface/ui-components/multi-select-sortable-item-content-ui',
				// 		'reference/interface/ui-components/navigation-guard-dialog',
				// 		'reference/interface/ui-components/ordered-list-renderer',
				// 		'reference/interface/ui-components/otp-setup',
				// 		'reference/interface/ui-components/outdated-application-dialog',
				// 		'reference/interface/ui-components/overlay',
				// 		'reference/interface/ui-components/paragraph-renderer',
				// 		'reference/interface/ui-components/password-reset-form-fields',
				// 		'reference/interface/ui-components/password-reset-request-form-fields',
				// 		'reference/interface/ui-components/passwordless-sign-in-form-fields',
				// 		'reference/interface/ui-components/passwordless-sign-in-init-form-fields',
				// 		'reference/interface/ui-components/persist-button',
				// 		'reference/interface/ui-components/person-list',
				// 		'reference/interface/ui-components/popover-anchor',
				// 		'reference/interface/ui-components/popover-content',
				// 		'reference/interface/ui-components/popover-trigger',
				// 		'reference/interface/ui-components/progress',
				// 		'reference/interface/ui-components/property-item',
				// 		'reference/interface/ui-components/property-label',
				// 		'reference/interface/ui-components/property-list',
				// 		'reference/interface/ui-components/property-row',
				// 		'reference/interface/ui-components/property-value',
				// 		'reference/interface/ui-components/radio-enum-field',
				// 		'reference/interface/ui-components/radio-input',
				// 		'reference/interface/ui-components/repeater-add-item-button',
				// 		'reference/interface/ui-components/repeater-drop-indicator',
				// 		'reference/interface/ui-components/repeater-item-actions',
				// 		'reference/interface/ui-components/repeater-remove-item-button',
				// 		'reference/interface/ui-components/rich-text-field',
				// 		'reference/interface/ui-components/rich-text-field-plugins',
				// 		'reference/interface/ui-components/rich-text-view',
				// 		'reference/interface/ui-components/scroll-area',
				// 		'reference/interface/ui-components/scroll-target-renderer',
				// 		'reference/interface/ui-components/select-content',
				// 		'reference/interface/ui-components/select-default-filter',
				// 		'reference/interface/ui-components/select-default-placeholder-ui',
				// 		'reference/interface/ui-components/select-enum-field',
				// 		'reference/interface/ui-components/select-field',
				// 		'reference/interface/ui-components/select-group',
				// 		'reference/interface/ui-components/select-input',
				// 		'reference/interface/ui-components/select-input-actions-ui',
				// 		'reference/interface/ui-components/select-input-ui',
				// 		'reference/interface/ui-components/select-input-wrapper-ui',
				// 		'reference/interface/ui-components/select-item',
				// 		'reference/interface/ui-components/select-list-inner',
				// 		'reference/interface/ui-components/select-list-item-ui',
				// 		'reference/interface/ui-components/select-popover-content',
				// 		'reference/interface/ui-components/select-trigger',
				// 		'reference/interface/ui-components/select-value',
				// 		'reference/interface/ui-components/separator',
				// 		'reference/interface/ui-components/sheet-content',
				// 		'reference/interface/ui-components/sheet-trigger',
				// 		'reference/interface/ui-components/side-dimensions',
				// 		'reference/interface/ui-components/sidebar',
				// 		'reference/interface/ui-components/sidebar-content',
				// 		'reference/interface/ui-components/sidebar-footer',
				// 		'reference/interface/ui-components/sidebar-group',
				// 		'reference/interface/ui-components/sidebar-group-action',
				// 		'reference/interface/ui-components/sidebar-group-content',
				// 		'reference/interface/ui-components/sidebar-group-label',
				// 		'reference/interface/ui-components/sidebar-header',
				// 		'reference/interface/ui-components/sidebar-inset',
				// 		'reference/interface/ui-components/sidebar-menu',
				// 		'reference/interface/ui-components/sidebar-menu-action',
				// 		'reference/interface/ui-components/sidebar-menu-button',
				// 		'reference/interface/ui-components/sidebar-menu-item',
				// 		'reference/interface/ui-components/sidebar-menu-skeleton',
				// 		'reference/interface/ui-components/sidebar-menu-sub',
				// 		'reference/interface/ui-components/sidebar-provider',
				// 		'reference/interface/ui-components/skeleton',
				// 		'reference/interface/ui-components/sortable-block',
				// 		'reference/interface/ui-components/sortable-multi-select-field',
				// 		'reference/interface/ui-components/sortable-multi-select-input',
				// 		'reference/interface/ui-components/standalone-form-container',
				// 		'reference/interface/ui-components/switch',
				// 		'reference/interface/ui-components/table',
				// 		'reference/interface/ui-components/table-body',
				// 		'reference/interface/ui-components/table-caption',
				// 		'reference/interface/ui-components/table-cell',
				// 		'reference/interface/ui-components/table-head',
				// 		'reference/interface/ui-components/table-header',
				// 		'reference/interface/ui-components/table-row',
				// 		'reference/interface/ui-components/table-wrapper',
				// 		'reference/interface/ui-components/textarea',
				// 		'reference/interface/ui-components/textarea-autosize',
				// 		'reference/interface/ui-components/textarea-field',
				// 		'reference/interface/ui-components/title',
				// 		'reference/interface/ui-components/toast-content',
				// 		'reference/interface/ui-components/toaster',
				// 		'reference/interface/ui-components/todo',
				// 		'reference/interface/ui-components/toggle',
				// 		'reference/interface/ui-components/toggle-group',
				// 		'reference/interface/ui-components/toggle-group-item',
				// 		'reference/interface/ui-components/tooltip-content',
				// 		'reference/interface/ui-components/tooltip-provider',
				// 		'reference/interface/ui-components/tooltip-trigger',
				// 		'reference/interface/ui-components/update-project-member-form-fields',
				// 		'reference/interface/ui-components/uploaded-any-view',
				// 		'reference/interface/ui-components/uploaded-audio-view',
				// 		'reference/interface/ui-components/uploaded-image-view',
				// 		'reference/interface/ui-components/uploaded-video-view',
				// 		'reference/interface/ui-components/uploader-dropzone',
				// 		'reference/interface/ui-components/uploader-dropzone-area-ui',
				// 		'reference/interface/ui-components/uploader-dropzone-wrapper-ui',
				// 		'reference/interface/ui-components/uploader-file-progress-ui',
				// 		'reference/interface/ui-components/uploader-item-ui',
				// 		'reference/interface/ui-components/uploader-progress',
				// 		'reference/interface/ui-components/use-invite-user',
				// 		'reference/interface/ui-components/use-persist-with-feedback',
				// 		'reference/interface/ui-components/use-show-toast',
				// 		'reference/interface/ui-components/video-field',
				// 		'reference/interface/ui-components/video-repeater-field',
				// 	],
				// },
			],
		},
		{
			type: 'category',
			label: 'Contember Engine',
			collapsed: true,
			items: [
				{
					type: 'category',
					label: 'Schema',
					collapsed: true,
					items: [
						'reference/engine/schema/overview',
						'reference/engine/schema/columns',
						'reference/engine/schema/relationships',
						'reference/engine/schema/views',
						'reference/engine/schema/acl',
						'reference/engine/schema/tenant-acl',
						'reference/engine/schema/validations',
					],
				},
				{
					type: 'category',
					label: 'Migrations',
					collapsed: true,
					items: [
						'reference/engine/migrations/overview',
						'reference/engine/migrations/basics',
						'reference/engine/migrations/content-migrations',
						{
							type: 'category',
							label: 'Advanced',
							items: [
								'reference/engine/migrations/advanced/development-commands',
								'reference/engine/migrations/advanced/skipping-validations',
								'reference/engine/migrations/advanced/writing-schema-migrations',
							],
						},
					],
				},
				{
					type: 'category',
					label: 'Content API',
					items: [
						'reference/engine/content/overview',
						'reference/engine/content/queries',
						'reference/engine/content/mutations',
						'reference/engine/content/s3',
						'reference/engine/content/event-log',
						'reference/engine/content/transfer',
						{
							type: 'category',
							label: 'Advanced',
							items: [
								'reference/engine/content/advanced/assume-identity',
								'reference/engine/content/advanced/assume-membership',
								'reference/engine/content/advanced/request-debugging',
								'reference/engine/content/advanced/caching',
							],
						},
					],
				},
				{
					type: 'category',
					label: 'Tenant API',
					items: [
						'reference/engine/tenant/overview',
						'reference/engine/tenant/sessions',
						'reference/engine/tenant/invites',
						'reference/engine/tenant/memberships',
						'reference/engine/tenant/api-keys',
						'reference/engine/tenant/idp',
						'reference/engine/tenant/passwordless',
						'reference/engine/tenant/mail-templates',
						'reference/engine/tenant/password-policy',
					],
				},
				{
					type: 'category',
					label: 'Actions',
					items: [
						{
							type: 'doc',
							id: 'reference/engine/actions/overview',
							label: 'Overview',
						},
						'reference/engine/actions/definition',
						'reference/engine/actions/managing',
						'reference/engine/actions/invocation',
					],
				},
			],
		},
		'reference/cli',
		{
			type: 'category',
			label: 'Contember Cloud',
			collapsed: true,
			items: [
				'guides/deploy-contember',
				'cloud/permissions',
			],
		},
		{
			type: 'category',
			label: 'Guides',
			collapsed: true,
			items: [
				'guides/deploy-github-actions',
				'guides/self-hosted-contember',
				'guides/seo',
				'guides/acl-definition',
				'guides/superface',
			],
		},
	],
}


export default sidebars
