import { InviteErrorCodes } from './hooks/useInvite.js'
import {
	AddProjectMemberFormErrorCode,
	ChangeMyPasswordFormErrorCode,
	ChangeMyProfileFormErrorCode,
	ChangePasswordFormErrorCode,
	ChangeProfileFormErrorCode,
	CreateApiKeyFormErrorCode,
	CreateGlobalApiKeyFormErrorCode,
	SetProjectSecretFormErrorCode,
} from '@contember/interface'
import {
	ConfirmEmailChangeFormErrorCode,
	EmailOtpConfirmFormErrorCode,
	InviteFormErrorCode,
	LoginFormErrorCode,
	OtpConfirmFormErrorCode,
	OtpPrepareFormErrorCode,
	PasswordlessSignInFormErrorCode,
	PasswordlessSignInInitFormErrorCode,
	PasswordResetFormErrorCode,
	PasswordResetRequestFormErrorCode,
	RequestEmailVerificationFormErrorCode,
	SignUpFormErrorCode,
	UpdateProjectMemberFormErrorCode,
	VerifyEmailFormErrorCode,
} from '@contember/react-identity'
import {
	ActivatePasswordlessOtpErrorCode,
	AddGlobalIdentityRolesErrorCode,
	DisconnectIDPErrorCode,
	RemoveGlobalIdentityRolesErrorCode,
} from '@contember/graphql-client-tenant'

export const dict = {
	inviteErrors: {
		ALREADY_MEMBER: 'This user is already a member of the project',
		INVALID_EMAIL_FORMAT: 'Invalid email format',
		INVALID_MEMBERSHIP: 'Invalid membership',
		PROJECT_NOT_FOUND: 'Project not found',
		ROLE_NOT_FOUND: 'Role not found',
		VARIABLE_EMPTY: 'Variable is empty',
		VARIABLE_NOT_FOUND: 'Variable not found',
		fallback: 'Failed to invite user',
	} satisfies Record<InviteErrorCodes | 'fallback', string>,
	tenant: {
		memberList: {
			failedToLoadData: 'Failed to load data',
			noResults: 'No results',
			previous: 'Previous',
			next: 'Next',
			roles: 'Roles',
			action: 'Action',
		},
		apiKeyList: {
			deleted: 'API key deleted',
			deleteFailed: 'Failed to delete API key',
			unnamed: 'Unnamed API key',
			noResults: 'No API keys',
			description: 'Description',
			role: 'Role',
			action: 'Action',
			deleteConfirmation: 'Are you sure you want to delete this API key?',
			deleteCancelAction: 'Cancel',
			deleteConfirmAction: 'Delete',
			type: 'Type',
			roles: 'Roles',
			status: 'Status',
			created: 'Created',
			lastUsed: 'Last used',
			expires: 'Expires',
			enabled: 'Enabled',
			disabled: 'Disabled',
			noRoles: 'None',
			never: 'Never',
			unknownType: 'Unknown',
			failedToLoadData: 'Failed to load data',
			disableConfirmation: 'Are you sure you want to disable this API key?',
			disableSuccess: 'API key disabled',
			disableFailed: 'Failed to disable API key',
			cancel: 'Cancel',
			disable: 'Disable',
		},
		createApiKey: {
			description: 'Description',
			roles: 'Roles',
			submit: 'Create API key',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'INVALID_MEMBERSHIP': 'Invalid membership',
				'PROJECT_NOT_FOUND': 'Project not found',
				'ROLE_NOT_FOUND': 'Role not found',
				'VARIABLE_EMPTY': 'Variable empty',
				'VARIABLE_NOT_FOUND': 'Variable not found',
			} satisfies Record<CreateApiKeyFormErrorCode, string>,
		},
		invite: {
			email: 'Email',
			name: 'Name',
			roles: 'Roles',
			submit: 'Invite',
			submitUnmanaged: 'Create member',
			addRole: 'Add new role',
			unmanaged: 'Do not send an invitation e-mail',
			unmanagedDescription: 'Creates the member directly. Leave the password empty to make them use a password reset.',
			password: 'Password',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'ALREADY_MEMBER': 'This person is already a member',
				'INVALID_EMAIL_FORMAT': 'Invalid email format',
				'INVALID_MEMBERSHIP': 'Invalid membership',
				'PROJECT_NOT_FOUND': 'Project not found',
				'ROLE_NOT_FOUND': 'Role not found',
				'VARIABLE_EMPTY': 'Variable empty',
				'VARIABLE_NOT_FOUND': 'Variable not found',
			} satisfies Record<InviteFormErrorCode, string>,
		},
		changePassword: {
			currentPassword: 'Current password',
			newPassword: 'New password',
			confirmPassword: 'Confirm password',
			submit: 'Change password',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'PASSWORD_MISMATCH': 'Passwords do not match',
				'TOO_WEAK': 'Password is too weak',
				'NO_PASSWORD_SET': 'Your account has no password set',
				'INVALID_PASSWORD': 'Invalid password',
				'NOT_A_PERSON': 'Invalid user',
			} satisfies Record<ChangeMyPasswordFormErrorCode, string>,
		},
		login: {
			email: 'Email',
			password: 'Password',
			otpToken: '2FA OTP token',
			backupCode: 'Backup code',
			backupCodeHint: 'Lost your authenticator? Use one of your backup codes instead.',
			forgotPassword: 'Forgot password?',
			login: 'Login',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'INVALID_PASSWORD': 'Invalid password',
				'INVALID_OTP_TOKEN': 'Invalid OTP token',
				'NO_PASSWORD_SET': 'No password set',
				'PERSON_DISABLED': 'Person disabled',
				'UNKNOWN_EMAIL': 'Unknown email',
				'INVALID_CREDENTIALS': 'Invalid credentials',
				'RATE_LIMIT_EXCEEDED': 'Too many failed attempts, please try again later',
				'OTP_REQUIRED': undefined,
				'MFA_ENROLLMENT_REQUIRED': 'Multi-factor authentication enrollment is required',
				'EMAIL_NOT_VERIFIED': 'Your e-mail address has not been verified',
			} satisfies Record<LoginFormErrorCode, string | undefined>,
			idpInitError: 'Failed to initialize IdP login:',
			idpResponseError: 'Failed to process IdP response:',
			title: 'Login',
			description: 'Enter your email below to login to your account',
			backToLogin: 'Back to login',
		},
		personList: {
			email: 'Email',
			name: 'Name',
			deleted: 'Member deleted',
			deleteFailed: 'Failed to delete member',
			noEmail: 'User has no email',
			noName: 'User has no name',
			role: 'Role',
			action: 'Action',
			noResults: 'No members',
			deleteConfirmation: 'Are you sure you want to delete this member?',
			deleteCancelAction: 'Cancel',
			deleteConfirmAction: 'Delete',
		},
		memberDelete: {
			cancel: 'Cancel',
			confirm: 'Confirm',
		},
		mfa: {
			totp: 'TOTP',
			email: 'Email OTP',
			none: 'None',
		},
		personsList: {
			email: 'Email',
			name: 'Name',
			roles: 'Roles',
			mfa: '2FA',
			noEmail: 'No email',
			noName: 'No name',
			noRoles: 'None',
			noResults: 'No users',
			failedToLoadData: 'Failed to load data',
			filterEmailPlaceholder: 'Filter by email',
			previous: 'Previous',
			next: 'Next',
			status: 'Status',
			active: 'Active',
			disabled: 'Disabled',
			actions: 'Actions',
		},
		globalApiKeyList: {
			description: 'Description',
			type: 'Type',
			status: 'Status',
			roles: 'Roles',
			created: 'Created',
			lastUsed: 'Last used',
			expires: 'Expires',
			action: 'Action',
			enabled: 'Enabled',
			disabled: 'Disabled',
			unnamed: 'Unnamed API key',
			noRoles: 'None',
			never: 'Never',
			noResults: 'No API keys',
			failedToLoadData: 'Failed to load data',
			previous: 'Previous',
			next: 'Next',
			disableConfirmation: 'Are you sure you want to disable this API key?',
			disableSuccess: 'API key disabled',
			disableFailed: 'Failed to disable API key',
			cancel: 'Cancel',
			disable: 'Disable',
		},
		createGlobalApiKey: {
			description: 'Description',
			roles: 'Roles',
			addRole: 'Add role',
			removeRole: 'Remove role',
			rolePlaceholder: 'Role name',
			submit: 'Create API key',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'INVALID_MEMBERSHIP': 'Invalid membership',
				'PROJECT_NOT_FOUND': 'Project not found',
				'ROLE_NOT_FOUND': 'Role not found',
				'VARIABLE_EMPTY': 'Variable empty',
				'VARIABLE_NOT_FOUND': 'Variable not found',
			} satisfies Record<CreateGlobalApiKeyFormErrorCode, string>,
		},
		projectSecretList: {
			key: 'Key',
			created: 'Created',
			updated: 'Updated',
			noResults: 'No secrets',
			failedToLoadData: 'Failed to load data',
		},
		configView: {
			failedToLoadData: 'Failed to load data',
			forbidden: 'You do not have permission to view this.',
			managedByCli: 'Read-only. Change this with',
			managedByCliCommand: 'contember tenant:apply',
			setting: 'Setting',
			value: 'Value',
			enabled: 'Enabled',
			disabled: 'Disabled',
			notSet: 'Not set',
			signup: 'Sign-up',
			emailChange: 'E-mail change',
			passwordless: 'Passwordless sign-in',
			password: 'Password policy',
			login: 'Login',
			anomalyDetection: 'Anomaly detection',
			captcha: 'Captcha',
			rateLimits: 'Rate limits',
			limit: 'Limit',
			window: 'Window',
		},
		authPolicyList: {
			scope: 'Scope',
			project: 'Project',
			roles: 'Roles',
			mfaRequired: 'MFA required',
			tokenExpiration: 'Token expiration',
			idleTimeout: 'Idle timeout',
			mfaGraceDuration: 'MFA grace',
			rememberMeAllowed: 'Remember me',
			noResults: 'No auth policies configured — MFA enforcement is inert.',
			failedToLoadData: 'Failed to load data',
			forbidden: 'You do not have permission to view auth policies.',
			aggregationNote: 'An identity is subject to every policy matching any of its roles; the strictest value wins.',
		},
		identityProviderList: {
			slug: 'Slug',
			type: 'Type',
			status: 'Status',
			configuration: 'Configuration',
			showConfiguration: 'Show configuration',
			hideConfiguration: 'Hide configuration',
			autoSignUp: 'Auto sign-up',
			exclusive: 'Exclusive',
			noResults: 'No identity providers configured',
			failedToLoadData: 'Failed to load data',
			forbidden: 'You do not have permission to view identity providers.',
			secretsNote: 'Secrets are stripped server-side for the built-in oidc, apple and facebook handlers.',
		},
		mailTemplateList: {
			type: 'Type',
			variant: 'Variant',
			project: 'Project',
			subject: 'Subject',
			replyTo: 'Reply to',
			useLayout: 'Layout',
			showContent: 'Show content',
			hideContent: 'Hide content',
			noResults: 'No custom mail templates — the built-in defaults are in use.',
			failedToLoadData: 'Failed to load data',
			forbidden: 'You do not have permission to view mail templates.',
		},
		changeMyProfile: {
			email: 'Email',
			name: 'Name',
			submit: 'Save changes',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'NOT_A_PERSON': 'Invalid user',
				'INVALID_EMAIL_FORMAT': 'Invalid email format',
				'EMAIL_ALREADY_EXISTS': 'This e-mail address is already in use',
				'RATE_LIMIT_EXCEEDED': 'Too many requests, please try again later',
			} satisfies Record<ChangeMyProfileFormErrorCode | 'UNKNOWN_ERROR', string>,
		},
		emailOtpSetup: {
			description: 'Get a one-time code by e-mail every time you sign in — a lightweight alternative to an authenticator app.',
			sendCode: 'Send code by e-mail',
			codeSent: 'A code has been sent to your e-mail address.',
			otpToken: 'E-mail code',
			confirm: 'Confirm',
			emailOtpConfirmFormErrorMessages: {
				INVALID_OTP_TOKEN: 'Invalid code',
				FIELD_REQUIRED: 'This field is required',
				INVALID_VALUE: 'Invalid value',
				UNKNOWN_ERROR: 'Something went wrong. Please try again later',
			} satisfies Record<EmailOtpConfirmFormErrorCode, string>,
			enabledSuccess: 'E-mail two-factor authentication was enabled.',
			emailOtpEnabled: 'E-mail two-factor authentication is ENABLED.',
			disableEmailOtp: 'Disable e-mail two-factor authentication',
			disableEmailOtpConfirm: 'Are you sure you want to disable e-mail two-factor authentication?',
			disable: 'Disable',
			disabledSuccess: 'E-mail two-factor authentication was disabled.',
			setupAgain: 'Send new code',
			cancel: 'Cancel',
			initFailed: 'Failed to send the code. Please try again later.',
			disableFailed: 'Failed to disable e-mail two-factor authentication.',
		},
		backupCodes: {
			description: 'Backup codes let you sign in if you lose access to your authenticator or e-mail codes.',
			regenerate: 'Regenerate backup codes',
			regenerateConfirm: 'Regenerating invalidates your existing backup codes. Are you sure you want to continue?',
			regenerateSuccess: 'New backup codes were generated.',
			regenerateFailed: 'Failed to generate new backup codes.',
			cancel: 'Cancel',
			noMfaActive: 'Backup codes are available once you enable two-factor authentication.',
			writeDownNote: 'Write these down and keep them somewhere safe. Each code works once.',
		},
		passwordlessToggle: {
			descriptionEnabled: 'Passwordless sign-in is ENABLED. You can sign in with a magic link sent to your e-mail, without a password.',
			descriptionDisabled: 'Enable passwordless sign-in to sign in with a magic link sent to your e-mail, without a password.',
			enable: 'Enable passwordless sign-in',
			disable: 'Disable passwordless sign-in',
			enabledSuccess: 'Passwordless sign-in was enabled.',
			disabledSuccess: 'Passwordless sign-in was disabled.',
			toggleFailed:
				'Could not change passwordless sign-in. If this is your only sign-in method, set a password or enable two-factor authentication first.',
		},
		sessionList: {
			failedToLoadData: 'Failed to load data',
			noResults: 'No active sessions',
			created: 'Created',
			lastUsed: 'Last used',
			ip: 'IP address',
			userAgent: 'Device',
			expires: 'Expires',
			action: 'Action',
			never: 'Never',
			thisDevice: 'This device',
			revoke: 'Revoke',
			revokeConfirmation: 'Are you sure you want to revoke this session? The device will be signed out.',
			revokeSuccess: 'Session revoked',
			revokeFailed: 'Failed to revoke session',
			cancel: 'Cancel',
		},
		otpSetup: {
			prepareContinue: 'Continue',
			otpConfirmFormErrorMessages: {
				UNKNOWN_ERROR: 'Something went wrong. Please try again later',
				INVALID_OTP_TOKEN: 'Invalid OTP token',
				FIELD_REQUIRED: 'This field is required',
				NOT_PREPARED: 'OTP setup was not initialized',
			} satisfies Record<OtpConfirmFormErrorCode, string>,
			otpPrepareFormErrorMessages: {
				UNKNOWN_ERROR: 'Something went wrong. Please try again later',
			} satisfies Record<OtpPrepareFormErrorCode, string>,
			alreadyHaveOtp: 'You already have two-factor authentication active. By clicking "Continue", the old one will no longer work.',
			nowScanQrCode: 'Now scan the following QR code in your application:',
			writeDownCode: 'After registering to your application, write down a code from the application.',
			twoFactorEnabled: 'Two factor authentication is ENABLED.',
			disableTwoFactor: 'Disable two-factor authentication',
			disableTwoFactorConfirm: 'Are you sure you want to disable two-factor authentication?',
			cancel: 'Cancel',
			disable: 'Disable',
			disabledSuccess: 'Two-factor authentication was disabled.',
			setupAgain: 'Setup again',
			description:
				'2-Step Verification provides stronger security for your account by requiring a second step of verification when you sign in. In addition to your password, you’ll also need a code generated by an application on your phone.',
			setupTwoFactor: 'Setup two-factor authentication',
			enabledSuccess: 'Two-factor authentication was enabled.',
			otpToken: 'OTP token',
			label: 'Label',
			confirm: 'Confirm',
		},

		signUp: {
			email: 'E-mail',
			name: 'Name',
			password: 'Password',
			passwordConfirmation: 'Confirm password',
			submit: 'Create account',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'PASSWORD_MISMATCH': 'Passwords do not match',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'EMAIL_ALREADY_EXISTS': 'An account with this e-mail already exists',
				'INVALID_EMAIL_FORMAT': 'Invalid e-mail format',
				'TOO_WEAK': 'Password is too weak',
				'INVALID_CAPTCHA': 'Captcha verification failed',
				'RATE_LIMIT_EXCEEDED': 'Too many attempts. Please try again later',
			} satisfies Record<SignUpFormErrorCode, string>,
			title: 'Create an account',
		},

		passwordReset: {
			token: 'Reset code',
			password: 'Password',
			passwordConfirmation: 'Confirm password',
			submit: 'Reset password',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'PASSWORD_MISMATCH': 'Passwords do not match',
				'PASSWORD_TOO_WEAK': 'Password is too weak',
				'TOKEN_EXPIRED': 'Token expired',
				'TOKEN_NOT_FOUND': 'Token not found',
				'TOKEN_USED': 'Token already used',
				'TOKEN_INVALID': 'Invalid token',
			} satisfies Record<PasswordResetFormErrorCode, string>,
			title: 'Reset password',
			description: 'Enter new password below',
			success: 'Password has been reset',
		},
		passwordResetRequest: {
			email: 'E-mail',
			submit: 'Request reset code',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'PERSON_NOT_FOUND': 'Unknown email',
				'RATE_LIMIT_EXCEEDED': 'Too many requests, please try again later',
				'INVALID_CAPTCHA': 'Captcha verification failed',
			} satisfies Record<PasswordResetRequestFormErrorCode, string>,
			title: 'Reset password',
			description: 'Enter your email below to reset your password',
			success: 'Password reset link has been sent',
			checkMail: 'Please check your mailbox for instructions on how to reset your password.',
			entryCode: 'Or enter the reset code directly.',
		},
		verifyEmail: {
			token: 'Verification code',
			submit: 'Verify e-mail',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'TOKEN_EXPIRED': 'Token expired',
				'TOKEN_NOT_FOUND': 'Token not found',
				'TOKEN_USED': 'Token already used',
				'TOKEN_INVALID': 'Invalid token',
			} satisfies Record<VerifyEmailFormErrorCode, string>,
			title: 'Verify e-mail',
			description: 'Enter the verification code to confirm your e-mail address',
			success: 'Your e-mail address has been verified',
		},
		confirmEmailChange: {
			token: 'Confirmation code',
			submit: 'Confirm e-mail change',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'TOKEN_EXPIRED': 'Token expired',
				'TOKEN_NOT_FOUND': 'Token not found',
				'TOKEN_USED': 'Token already used',
				'TOKEN_INVALID': 'Invalid token',
				'EMAIL_ALREADY_EXISTS': 'This e-mail address is already in use',
				'INVALID_EMAIL_FORMAT': 'Invalid email format',
			} satisfies Record<ConfirmEmailChangeFormErrorCode, string>,
			title: 'Confirm e-mail change',
			description: 'Enter the confirmation code to change your e-mail address',
			success: 'Your e-mail address has been changed',
		},
		requestEmailVerification: {
			email: 'E-mail',
			submit: 'Send verification link',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'RATE_LIMIT_EXCEEDED': 'Too many requests, please try again later',
				'INVALID_CAPTCHA': 'Captcha verification failed',
			} satisfies Record<RequestEmailVerificationFormErrorCode, string>,
			title: 'Verify e-mail',
			description: 'Enter your e-mail below to receive a verification link',
			success: 'Verification link has been sent',
			checkMail: 'Please check your mailbox for instructions on how to verify your e-mail address.',
			entryCode: 'Or enter the verification code directly.',
		},
		passwordlessSignInInit: {
			email: 'E-mail',
			submit: 'Send magic link',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'PERSON_NOT_FOUND': 'Unknown email',
				'PASSWORDLESS_DISABLED': 'Passwordless sign-in is not available',
				'RATE_LIMIT_EXCEEDED': 'Too many requests, please try again later',
				'INVALID_CAPTCHA': 'Captcha verification failed',
			} satisfies Record<PasswordlessSignInInitFormErrorCode, string>,
			title: 'Sign in',
			description: 'Enter your email below to sign in to your account',
			success: 'Magic link has been sent',
			checkMail: 'Please check your mailbox for instructions on how to sign in.',
			entryCode: 'Or enter the reset code directly.',
		},
		passwordlessSignIn: {
			token: 'Verification code',
			otpToken: '2FA OTP token',
			backupCode: 'Backup code',
			backupCodeHint: 'Lost your authenticator? Use one of your backup codes instead.',
			submit: 'Sign in',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'INVALID_OTP_TOKEN': 'Invalid OTP token',
				'OTP_REQUIRED': undefined,
				'PERSON_DISABLED': 'Person disabled',
				'TOKEN_EXPIRED': 'Token expired',
				'TOKEN_NOT_FOUND': 'Token not found',
				'TOKEN_USED': 'Token already used',
				'TOKEN_INVALID': 'Invalid token',
				'MFA_ENROLLMENT_REQUIRED': 'Multi-factor authentication enrollment is required',
			} satisfies Record<PasswordlessSignInFormErrorCode, string | undefined>,
			title: 'Sign in',
		},
		otpActivation: {
			errorMessages: {
				'TOKEN_INVALID': 'This token is not valid. Please try again.',
				'TOKEN_USED': 'Token already used',
				'TOKEN_NOT_FOUND': 'Token not found',
				'TOKEN_EXPIRED': 'Token expired',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
			} satisfies Record<ActivatePasswordlessOtpErrorCode | 'UNKNOWN_ERROR', string>,
		},

		updateProjectMember: {
			updateSuccess: 'Roles updated',
			roles: 'Roles',
			submit: 'Update role',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'INVALID_MEMBERSHIP': 'Invalid membership',
				'PROJECT_NOT_FOUND': 'Project not found',
				'ROLE_NOT_FOUND': 'Role not found',
				'VARIABLE_EMPTY': 'Variable empty',
				'VARIABLE_NOT_FOUND': 'Variable not found',
				'NOT_MEMBER': 'Not a member',
			} satisfies Record<UpdateProjectMemberFormErrorCode, string>,
		},
		personActions: {
			cancel: 'Cancel',
			disable: 'Disable',
			disableTitle: 'Disable person',
			disableConfirmation: 'Are you sure you want to disable this person? They will not be able to sign in.',
			disableSuccess: 'Person disabled',
			disableFailed: 'Failed to disable the person',
			enable: 'Enable',
			enableTitle: 'Enable person',
			enableConfirmation: 'Are you sure you want to enable this person? They will be able to sign in again.',
			enableSuccess: 'Person enabled',
			enableFailed: 'Failed to enable the person',
			forceSignOut: 'Sign out',
			forceSignOutTitle: 'Force sign out',
			forceSignOutConfirmation: 'Are you sure you want to sign this person out of all their sessions?',
			forceSignOutReason: 'Reason (optional)',
			forceSignOutReasonPlaceholder: 'Recorded in the audit log',
			forceSignOutSuccess: 'Person signed out of all sessions',
			forceSignOutFailed: 'Failed to sign the person out',
			resetMfa: 'Reset 2FA',
			resetMfaTitle: 'Reset two-factor authentication',
			resetMfaConfirmation:
				'Are you sure you want to reset two-factor authentication? This clears the TOTP authenticator, e-mail OTP and all backup codes.',
			resetMfaSuccess: 'Two-factor authentication was reset',
			resetMfaFailed: 'Failed to reset two-factor authentication',
		},
		personDetail: {
			failedToLoadData: 'Failed to load data',
			notFound: 'Person not found',
			profile: 'Profile',
			profileUpdated: 'Profile updated',
			password: 'Password',
			passwordUpdated: 'Password updated',
			mfa: 'Two-factor authentication',
			globalRoles: 'Global roles',
			sessions: 'Sessions',
			identityProviders: 'Identity providers',
			identityProvider: 'Provider',
			identityProviderAccount: 'External account',
			identityProviderConnectedAt: 'Connected',
			identityProviderStatus: 'Status',
			identityProviderDisabled: 'Disabled',
			noIdentityProviders: 'No connected identity providers',
		},
		globalRoles: {
			noRoles: 'No global roles',
			rolePlaceholder: 'Role name',
			addRole: 'Add role',
			removeRole: 'Remove role',
			addSuccess: 'Global role added',
			removeSuccess: 'Global role removed',
			errorMessages: {
				'IDENTITY_NOT_FOUND': 'This identity no longer exists',
				'INVALID_ROLE': 'This role is not defined in the tenant configuration',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
			} satisfies Record<AddGlobalIdentityRolesErrorCode | RemoveGlobalIdentityRolesErrorCode | 'UNKNOWN_ERROR', string>,
		},
		changeProfile: {
			email: 'E-mail',
			name: 'Name',
			submit: 'Save profile',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'PERSON_NOT_FOUND': 'This person no longer exists',
				'INVALID_EMAIL_FORMAT': 'Invalid email format',
				'EMAIL_ALREADY_EXISTS': 'This e-mail address is already in use',
			} satisfies Record<ChangeProfileFormErrorCode, string>,
		},
		setPersonPassword: {
			password: 'New password',
			passwordConfirmation: 'Confirm password',
			submit: 'Set password',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'INVALID_VALUE': 'Invalid value',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'PASSWORD_MISMATCH': 'Passwords do not match',
				'TOO_WEAK': 'Password is too weak',
				'PERSON_NOT_FOUND': 'This person no longer exists',
			} satisfies Record<ChangePasswordFormErrorCode, string>,
		},
		setProjectSecret: {
			key: 'Key',
			value: 'Value',
			submit: 'Set secret',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'PROJECT_NOT_FOUND': 'Project not found',
			} satisfies Record<SetProjectSecretFormErrorCode, string>,
		},
		addProjectMember: {
			identityId: 'Identity ID',
			roles: 'Roles',
			submit: 'Add member',
			errorMessages: {
				'FIELD_REQUIRED': 'This field is required',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
				'ALREADY_MEMBER': 'This identity is already a member of the project',
				'IDENTITY_NOT_FOUND': 'Identity not found',
				'INVALID_MEMBERSHIP': 'Invalid membership',
				'PROJECT_NOT_FOUND': 'Project not found',
				'ROLE_NOT_FOUND': 'Role not found',
				'VARIABLE_EMPTY': 'Variable empty',
				'VARIABLE_NOT_FOUND': 'Variable not found',
			} satisfies Record<AddProjectMemberFormErrorCode, string>,
		},
		authLog: {
			createdAt: 'Created',
			type: 'Type',
			success: 'Result',
			person: 'Person',
			ipAddress: 'IP address',
			errorCode: 'Error',
			action: 'Action',
			ok: 'OK',
			failed: 'Failed',
			filterTypes: 'Event types',
			filterTypesPlaceholder: 'e.g. sign_in, sign_in_error (comma separated)',
			filterSuccess: 'Result',
			filterSuccessAll: 'All',
			filterSuccessOk: 'Successful only',
			filterSuccessFailed: 'Failed only',
			filterPerson: 'Person identifier',
			filterPersonPlaceholder: 'E-mail or identifier used to sign in',
			noResults: 'No entries',
			forbidden: 'You do not have permission to view the auth log.',
			failedToLoadData: 'Failed to load data',
			previous: 'Previous',
			next: 'Next',
		},
		identityProviderConnections: {
			provider: 'Provider',
			account: 'External account',
			connectedAt: 'Connected',
			status: 'Status',
			disabled: 'Disabled',
			action: 'Action',
			disconnect: 'Disconnect',
			disconnectConfirmation: 'Are you sure you want to disconnect this identity provider?',
			disconnected: 'Identity provider disconnected',
			cancel: 'Cancel',
			noResults: 'No connected identity providers',
			failedToLoadData: 'Failed to load data',
			errorMessages: {
				'NOT_FOUND': 'This identity provider connection no longer exists',
				'NOT_A_PERSON': 'Only a signed-in person can disconnect identity providers',
				'LAST_AUTH_METHOD': 'You cannot disconnect your last remaining sign-in method',
				'UNKNOWN_ERROR': 'Something went wrong. Please try again later',
			} satisfies Record<DisconnectIDPErrorCode | 'UNKNOWN_ERROR', string>,
		},
	},
}
