export const VERSION_INITIAL = 1
export const VERSION_LATEST = 5

export const VERSION_ACL_PATCH = 2
export const VERSION_UPDATE_CONSTRAINT_FIELDS = 2
export const VERSION_REMOVE_RELATION_INVERSE_SIDE = 3
export const VERSION_REMOVE_REFERENCING_RELATIONS = 3
export const _REMOVED_VERSION_UPDATE_CONSTRAINT_NAME_ONE_HAS_ONE = 4
export const VERSION_UPDATE_INDEX_FIELDS = 5
