export const VERSION_INITIAL = 1
export const VERSION_LATEST = 3

export const VERSION_ACL_PATCH = 2
export const VERSION_UPDATE_CONSTRAINT_NAME = 2
export const VERSION_REMOVE_RELATION_INVERSE_SIDE = 3
export const VERSION_REMOVE_REFERENCING_RELATIONS = 3
