export const PASSWORD_RESET_EXPIRATION_MINUTES = 60
export const INVITATION_RESET_TOKEN_EXPIRATION_MINUTES = 60 * 24
export const EMAIL_VERIFICATION_EXPIRATION_MINUTES = 60 * 24
export const EMAIL_CHANGE_EXPIRATION_MINUTES = 60 * 24
